// <auto-generated />
using System;
using ClaimBase.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClaimBase.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClaimBase.Domain.Academic.Campus", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Campuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Campuses_Name", "char_length(\"Name\") > 0");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("QualificationId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("QualificationId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Courses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Courses_Code", "char_length(\"Code\") > 0");

                            t.HasCheckConstraint("CK_Courses_Name", "char_length(\"Name\") > 0");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("TenantId", "FacultyId", "Name")
                        .IsUnique();

                    b.ToTable("Departments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Departments_Name", "char_length(\"Name\") > 0");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.Faculty", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("CampusId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.HasIndex("TenantId", "CampusId", "Name")
                        .IsUnique();

                    b.ToTable("Faculties", null, t =>
                        {
                            t.HasCheckConstraint("CK_Faculties_Name", "char_length(\"Name\") > 0");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.PositionTitle", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("PositionTitles", null, t =>
                        {
                            t.HasCheckConstraint("CK_PositionTitles_Name", "char_length(\"Name\") > 0");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.Qualification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Qualifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Qualifications_Name", "char_length(\"Name\") > 0");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.Semester", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("Semesters", null, t =>
                        {
                            t.HasCheckConstraint("CK_Semesters_Dates", "\"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("CK_Semesters_Name", "char_length(\"Name\") > 0");

                            t.HasCheckConstraint("CK_Semesters_Status", "\"Status\" IN ('Draft', 'Open', 'Closed')");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.Staff", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("BiometricId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StaffNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BiometricId")
                        .IsUnique();

                    b.HasIndex("TenantId", "StaffNumber")
                        .IsUnique();

                    b.ToTable("Staff", null, t =>
                        {
                            t.HasCheckConstraint("CK_Staff_DisplayName", "char_length(\"DisplayName\") > 0");

                            t.HasCheckConstraint("CK_Staff_EmploymentType", "\"EmploymentType\" IN ('PartTime', 'FullTime')");

                            t.HasCheckConstraint("CK_Staff_StaffNumber", "char_length(\"StaffNumber\") > 0");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.StaffDepartment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TenantId", "DepartmentId");

                    b.HasIndex("TenantId", "StaffId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("StaffDepartments", (string)null);
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.StaffPosition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("PositionTitleId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("PositionTitleId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TenantId", "StaffId", "EffectiveFrom");

                    b.ToTable("StaffPositions", null, t =>
                        {
                            t.HasCheckConstraint("CK_StaffPositions_Range", "\"EffectiveTo\" IS NULL OR \"EffectiveTo\" > \"EffectiveFrom\"");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_PasswordResetTokens_OneOutstanding")
                        .HasFilter("\"UsedAt\" IS NULL");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("PasswordResetTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_PasswordResetTokens_Expiry", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_PasswordResetTokens_TokenHash", "char_length(\"TokenHash\") = 64");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Identity.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Tenants", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tenants_CurrencyCode", "char_length(\"CurrencyCode\") = 3");

                            t.HasCheckConstraint("CK_Tenants_Name", "char_length(\"Name\") > 0");

                            t.HasCheckConstraint("CK_Tenants_TimeZoneId", "char_length(\"TimeZoneId\") > 0");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StaffId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_DisplayName", "char_length(\"DisplayName\") > 0");

                            t.HasCheckConstraint("CK_Users_Email", "char_length(\"Email\") > 0");

                            t.HasCheckConstraint("CK_Users_HodDepartment", "\"Role\" <> 'HeadOfDepartment' OR \"DepartmentId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Users_LecturerStaff", "\"Role\" <> 'Lecturer' OR \"StaffId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('TenantAdmin', 'Admin', 'HeadOfDepartment', 'Finance', 'Lecturer')");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Rates.TeachingRate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("PositionTitleId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("QualificationId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("PositionTitleId");

                    b.HasIndex("QualificationId");

                    b.HasIndex("TenantId", "PositionTitleId", "QualificationId", "EffectiveFrom");

                    b.ToTable("TeachingRates", null, t =>
                        {
                            t.HasCheckConstraint("CK_TeachingRates_Amount", "\"Amount\" >= 0");

                            t.HasCheckConstraint("CK_TeachingRates_Range", "\"EffectiveTo\" IS NULL OR \"EffectiveTo\" > \"EffectiveFrom\"");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Rates.TransportRate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EffectiveFrom");

                    b.ToTable("TransportRates", null, t =>
                        {
                            t.HasCheckConstraint("CK_TransportRates_Amount", "\"Amount\" >= 0");

                            t.HasCheckConstraint("CK_TransportRates_Range", "\"EffectiveTo\" IS NULL OR \"EffectiveTo\" > \"EffectiveFrom\"");
                        });
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.Course", b =>
                {
                    b.HasOne("ClaimBase.Domain.Academic.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.Department", b =>
                {
                    b.HasOne("ClaimBase.Domain.Academic.Faculty", null)
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.Faculty", b =>
                {
                    b.HasOne("ClaimBase.Domain.Academic.Campus", null)
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.StaffDepartment", b =>
                {
                    b.HasOne("ClaimBase.Domain.Academic.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimBase.Domain.Academic.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimBase.Domain.Academic.StaffPosition", b =>
                {
                    b.HasOne("ClaimBase.Domain.Academic.PositionTitle", null)
                        .WithMany()
                        .HasForeignKey("PositionTitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimBase.Domain.Academic.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimBase.Domain.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("ClaimBase.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimBase.Domain.Identity.User", b =>
                {
                    b.HasOne("ClaimBase.Domain.Academic.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimBase.Domain.Academic.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ClaimBase.Domain.Rates.TeachingRate", b =>
                {
                    b.HasOne("ClaimBase.Domain.Academic.PositionTitle", null)
                        .WithMany()
                        .HasForeignKey("PositionTitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimBase.Domain.Academic.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
